import { getDeviceGroup } from "../utils/device";

export const getDropdownStyles = (width, height) => {
  const deviceGroup = getDeviceGroup(width, height);

  const deviceGroupStyles = {
    group1: {
      inputGroup: "mb-5",
      label: " mb-1.5 text-gray-800",
      dropdownButton: "flex-row justify-between items-center border border-gray-300 rounded-lg p-3 bg-white",
      dropdownText: " text-gray-800",
      dropdownPlaceholder: " text-gray-800",
      modalOverlay: "flex-1 justify-center bg-black/50",
      modalContent: "bg-white rounded-xl px-4 pb-4 mx-4 max-h-[70%]",
      modalHeader: "flex-row justify-between items-center py-3 border-b border-gray-200",
      modalTitle: "text-base font-semibold text-gray-800",
      optionsContainer: "max-h-80",
      optionItem: "py-3 border-b border-gray-200",
      selectedOption: "bg-blue-50",
      optionText: " text-gray-800",
      selectedOptionText: "text-[#4052FF] font-medium"
    },
    group2: {
      inputGroup: "mb-5",
      label: " mb-1.5 text-gray-800",
      dropdownButton: "flex-row justify-between items-center border border-gray-300 rounded-lg p-3 bg-white",
      dropdownText: " text-gray-800",
      dropdownPlaceholder: " text-gray-800",
      modalOverlay: "flex-1 justify-center bg-black/50",
      modalContent: "bg-white rounded-xl px-4 pb-4 mx-4 max-h-[70%]",
      modalHeader: "flex-row justify-between items-center py-3 border-b border-gray-200",
      modalTitle: "text-base font-semibold text-gray-800",
      optionsContainer: "max-h-80",
      optionItem: "py-3 border-b border-gray-200",
      selectedOption: "bg-blue-50",
      optionText: " text-gray-800",
      selectedOptionText: "text-[#4052FF] font-medium"
    },
    group3: {
      inputGroup: "mb-5",
      label: " mb-1.5 text-gray-800",
      dropdownButton: "flex-row justify-between items-center border border-gray-300 rounded-lg p-3 bg-white",
      dropdownText: " text-gray-800",
      dropdownPlaceholder: " text-gray-800",
      modalOverlay: "flex-1 justify-center bg-black/50",
      modalContent: "bg-white rounded-xl px-4 pb-4 mx-4 max-h-[70%]",
      modalHeader: "flex-row justify-between items-center py-3 border-b border-gray-200",
      modalTitle: "text-base font-semibold text-gray-800",
      optionsContainer: "max-h-80",
      optionItem: "py-3 border-b border-gray-200",
      selectedOption: "bg-blue-50",
      optionText: " text-gray-800",
      selectedOptionText: "text-[#4052FF] font-medium"
    },
    group4: {
      inputGroup: "mb-5",
      label: "text-base mb-2 text-gray-800",
      dropdownButton: "flex-row justify-between items-center border border-gray-300 rounded-lg p-3 bg-white",
      dropdownText: " text-gray-800",
      dropdownPlaceholder: " text-gray-800",
      modalOverlay: "flex-1 justify-center bg-black/50",
      modalContent: "bg-white rounded-xl px-4 pb-5 mx-5 max-h-[60%]",
      modalHeader: "flex-row justify-between items-center py-4 border-b border-gray-200",
      modalTitle: "text-lg font-semibold text-gray-800",
      optionsContainer: "max-h-80",
      optionItem: "py-3.5 border-b border-gray-200",
      selectedOption: "bg-blue-50",
      optionText: " text-gray-800",
      selectedOptionText: "text-[#4052FF] font-medium"
    },
    group5: {
      inputGroup: "mb-5",
      label: "text-base mb-2 text-gray-800",
      dropdownButton: "flex-row justify-between items-center border border-gray-300 rounded-lg p-3 bg-white",
      dropdownText: " text-gray-800",
      dropdownPlaceholder: " text-gray-800",
      modalOverlay: "flex-1 justify-center bg-black/50",
      modalContent: "bg-white rounded-xl px-4 pb-5 mx-5 max-h-[60%]",
      modalHeader: "flex-row justify-between items-center py-4 border-b border-gray-200",
      modalTitle: "text-lg font-semibold text-gray-800",
      optionsContainer: "max-h-96",
      optionItem: "py-3.5 border-b border-gray-200",
      selectedOption: "bg-blue-50",
      optionText: " text-gray-800",
      selectedOptionText: "text-[#4052FF] font-medium"
    },
    group6: {
      inputGroup: "mb-5",
      label: "text-base mb-2 text-gray-800",
      dropdownButton: "flex-row justify-between items-center border border-gray-300 rounded-lg p-3 bg-white",
      dropdownText: " text-gray-800",
      dropdownPlaceholder: " text-gray-800",
      modalOverlay: "flex-1 justify-center bg-black/50",
      modalContent: "bg-white rounded-xl px-4 pb-5 mx-5 max-h-[60%]",
      modalHeader: "flex-row justify-between items-center py-4 border-b border-gray-200",
      modalTitle: "text-lg font-semibold text-gray-800",
      optionsContainer: "max-h-96",
      optionItem: "py-3.5 border-b border-gray-200",
      selectedOption: "bg-blue-50",
      optionText: " text-gray-800",
      selectedOptionText: "text-[#4052FF] font-medium"
    },
    group7: {
      inputGroup: "mb-5",
      label: "text-base mb-2 text-gray-800",
      dropdownButton: "flex-row justify-between items-center border border-gray-300 rounded-lg p-3 bg-white",
      dropdownText: " text-gray-800",
      dropdownPlaceholder: " text-gray-800",
      modalOverlay: "flex-1 justify-center bg-black/50",
      modalContent: "bg-white rounded-xl px-4 pb-5 mx-5 max-h-[60%]",
      modalHeader: "flex-row justify-between items-center py-4 border-b border-gray-200",
      modalTitle: "text-lg font-semibold text-gray-800",
      optionsContainer: "max-h-96",
      optionItem: "py-3.5 border-b border-gray-200",
      selectedOption: "bg-blue-50",
      optionText: " text-gray-800",
      selectedOptionText: "text-[#4052FF] font-medium"
    },
    group8: {
      inputGroup: "mb-5",
      label: "text-base mb-2 text-gray-800",
      dropdownButton: "flex-row justify-between items-center border border-gray-300 rounded-lg p-3 bg-white",
      dropdownText: " text-gray-800",
      dropdownPlaceholder: " text-gray-800",
      modalOverlay: "flex-1 justify-center bg-black/50",
      modalContent: "bg-white rounded-xl px-4 pb-5 mx-5 max-h-[60%]",
      modalHeader: "flex-row justify-between items-center py-4 border-b border-gray-200",
      modalTitle: "text-lg font-semibold text-gray-800",
      optionsContainer: "max-h-96",
      optionItem: "py-3.5 border-b border-gray-200",
      selectedOption: "bg-blue-50",
      optionText: " text-gray-800",
      selectedOptionText: "text-[#4052FF] font-medium"
    },
    group9: {
      inputGroup: "mb-5",
      label: "text-base mb-2 text-gray-800",
      dropdownButton: "flex-row justify-between items-center border border-gray-300 rounded-lg p-3 bg-white",
      dropdownText: " text-gray-800",
      dropdownPlaceholder: " text-gray-800",
      modalOverlay: "flex-1 justify-center bg-black/50",
      modalContent: "bg-white rounded-xl px-4 pb-5 mx-5 max-h-[60%]",
      modalHeader: "flex-row justify-between items-center py-4 border-b border-gray-200",
      modalTitle: "text-lg font-semibold text-gray-800",
      optionsContainer: "max-h-96",
      optionItem: "py-3.5 border-b border-gray-200",
      selectedOption: "bg-blue-50",
      optionText: " text-gray-800",
      selectedOptionText: "text-[#4052FF] font-medium"
    },
    group10: {
      inputGroup: "mb-5",
      label: "text-base mb-2 text-gray-800",
      dropdownButton: "flex-row justify-between items-center border border-gray-300 rounded-lg p-3 bg-white",
      dropdownText: " text-gray-800",
      dropdownPlaceholder: " text-gray-800",
      modalOverlay: "flex-1 justify-center bg-black/50",
      modalContent: "bg-white rounded-xl px-4 pb-5 mx-5 max-h-[60%]",
      modalHeader: "flex-row justify-between items-center py-4 border-b border-gray-200",
      modalTitle: "text-lg font-semibold text-gray-800",
      optionsContainer: "max-h-96",
      optionItem: "py-3.5 border-b border-gray-200",
      selectedOption: "bg-blue-50",
      optionText: " text-gray-800",
      selectedOptionText: "text-[#4052FF] font-medium"
    },
    unknown: {
      inputGroup: "mb-5",
      label: "text-base mb-2 text-gray-800",
      dropdownButton: "flex-row justify-between items-center border border-gray-300 rounded-lg p-3 bg-white",
      dropdownText: " text-gray-800",
      dropdownPlaceholder: " text-gray-800",
      modalOverlay: "flex-1 justify-center bg-black/50",
      modalContent: "bg-white rounded-xl px-4 pb-5 mx-5 max-h-[60%]",
      modalHeader: "flex-row justify-between items-center py-4 border-b border-gray-200",
      modalTitle: "text-lg font-semibold text-gray-800",
      optionsContainer: "max-h-96",
      optionItem: "py-3.5 border-b border-gray-200",
      selectedOption: "bg-blue-50",
      optionText: " text-gray-800",
      selectedOptionText: "text-[#4052FF] font-medium"
    }
  };

  return deviceGroupStyles[deviceGroup];
};