import { getDeviceGroup } from "../utils/device";

export const getStyles = (width, height) => {
  const deviceGroup = getDeviceGroup(width, height);

  const deviceGroupStyles = {
    group1: {
      termsContainer: "flex-row flex-wrap justify-center items-center mt-4 px-4",
      termsText: "text-xs text-gray-600 text-center",
      termsLink: "text-xs text-[#4051FF] text-center",
      screen: "flex-1 bg-white",
      subscribeBanner: "absolute w-full bg-black pt-14 sm:pt-16 pb-3 items-center justify-center active:bg-neutral-800 active:scale-[0.98]",
      subscribeBannerText: "text-white text-sm sm:text-base",
      mainWrapper: "flex-[2] px-10 mt-40 items-center justify-center pb-0.5",
      contentWrapper: "w-full",
      bottomWrapper: "flex-1 px-16 pt-10 justify-start",
      headerText: "text-3xl text-center mb-4 font-bold text-black",
      subHeader: "px-10 text-sm mb-6",
      subHeaderText: "text-gray-800 text-center",
      authButton: "py-3 px-4 flex-row items-center justify-center rounded-[10px] mb-5",
      authButtonText: "text-base font-medium",
      authButtonActive: "bg-black active:bg-neutral-800 active:scale-[0.98]",
      authButtonTextColor: "text-white",
      videoView: "",
      videoViewContainer: "items-center justify-center",
      videoHeight: 200,
      videoWidth: width * 0.95,
      icon: "w-5 h-5 mr-3",
      iconMaterial: "mr-3"
    },
    group2: {
      termsContainer: "flex-row flex-wrap justify-center items-center   px-2 ",
      termsText: "text-xs text-gray-600 text-center",
      termsLink: "text-xs text-[#4051FF] text-center",
      screen: "flex-1 bg-white",
      subscribeBanner: "absolute w-full bg-black pt-14 sm:pt-16 pb-3 items-center justify-center active:bg-neutral-800 active:scale-[0.98]",
      subscribeBannerText: "text-white text-sm sm:text-base",
      mainWrapper: "flex-[2] px-10 mt-32 items-center justify-center pb-0.5",
      contentWrapper: "w-full",
      bottomWrapper: "flex-1 px-16 pt-10 justify-start",
      headerText: "text-3xl text-center px-10 mb-4 font-bold text-black",
      subHeader: "px-10 text-sm mb-6",
      subHeaderText: "text-gray-800 text-center",
      authButton: "py-3 px-4 flex-row items-center justify-center rounded-[10px] mb-5",
      authButtonText: "text-base font-medium",
      authButtonActive: "bg-black active:bg-neutral-800 active:scale-[0.98]",
      authButtonTextColor: "text-white",
      videoView: "",
      videoViewContainer: "items-center justify-center",
      videoHeight: 200,
      videoWidth: width * 0.95,
      icon: "w-5 h-5 mr-3",
      iconMaterial: "mr-3"
    },
    group3: {
      termsContainer: "flex-row flex-wrap justify-center items-center mt-2 ",
      termsText: "text-sm text-gray-600 text-center",
      termsLink: "text-sm text-[#4051FF] text-center",
      screen: "flex-1 bg-white",
      subscribeBanner: "absolute w-full bg-black pt-14 sm:pt-16 pb-3 items-center justify-center active:bg-neutral-800 active:scale-[0.98]",
      subscribeBannerText: "text-white text-sm sm:text-base",
      mainWrapper: "flex-[2] px-10 mt-24 items-center justify-center pb-0.5",
      contentWrapper: "w-full",
      bottomWrapper: "flex-1 px-16 pt-10 justify-start",
      headerText: "text-3xl text-center mb-4 px-10 font-bold text-black",
      subHeader: "px-10 text-sm mb-6",
      subHeaderText: "text-gray-800 text-center",
      authButton: "py-3 px-4 flex-row items-center justify-center rounded-[10px] mb-5",
      authButtonText: "text-base font-medium",
      authButtonActive: "bg-black active:bg-neutral-800 active:scale-[0.98]",
      authButtonTextColor: "text-white",
      videoView: "",
      videoViewContainer: "items-center justify-center",
      videoHeight: 200,
      videoWidth: width * 0.95,
      icon: "w-5 h-5 mr-3",
      iconMaterial: "mr-3"
    },
    group4: {
      termsContainer: "flex-row flex-wrap justify-center items-center mt-2 px-4",
      termsText: "text-base text-gray-600 text-center",
      termsLink: "text-base text-[#4051FF] text-center",
      screen: "flex-1 bg-white",
      subscribeBanner: "absolute w-full bg-black pt-14 sm:pt-16 pb-3 items-center justify-center active:bg-neutral-800 active:scale-[0.98]",
      subscribeBannerText: "text-white text-sm sm:text-base",
      mainWrapper: "flex-[2] px-12 pt-36 items-center justify-center",
      contentWrapper: "w-full",
      bottomWrapper: "flex-1 px-16 justify-start pt-4 mb-4",
      headerText: "text-4xl text-center mb-6 px-6 font-bold text-black",
      subHeader: "px-2 text-lg mb-6",
      subHeaderText: "text-gray-800 text-center",
      authButton: "py-4 px-4 flex-row items-center justify-center rounded-[10px] mb-5",
      authButtonText: "text-lg font-medium",
      authButtonActive: "bg-black active:bg-neutral-800 active:scale-[0.98]",
      authButtonTextColor: "text-white",
      videoView: "mt-4",
      videoViewContainer: "items-center justify-center",
      videoHeight: 240,
      videoWidth: width * 0.95,
      icon: "w-5 h-5 mr-3",
      iconMaterial: "mr-3"
    },
    group5: {
      termsContainer: "flex-row flex-wrap justify-center items-center mt-2 px-4",
      termsText: "text-base text-gray-600 text-center",
      termsLink: "text-base text-[#4051FF] text-center",
      screen: "flex-1 bg-white",
      subscribeBanner: "absolute w-full bg-black pt-14 sm:pt-16 pb-3 items-center justify-center active:bg-neutral-800 active:scale-[0.98]",
      subscribeBannerText: "text-white text-sm sm:text-base",
      mainWrapper: "flex-[2] px-12 pt-36 items-center justify-center",
      contentWrapper: "w-full",
      bottomWrapper: "flex-1 px-16 justify-start pt-2 mb-7",
      headerText: "text-4xl text-center px-6 mb-6 font-bold text-black",
      subHeader: "px-2 text-lg mb-6",
      subHeaderText: "text-gray-800 text-center",
      authButton: "py-4 px-4 flex-row items-center justify-center rounded-[10px] mb-6",
      authButtonText: "text-lg font-medium",
      authButtonActive: "bg-black active:bg-neutral-800 active:scale-[0.98]",
      authButtonTextColor: "text-white",
      videoView: "mt-4",
      videoViewContainer: "items-center justify-center",
      videoHeight: 260,
      videoWidth: width * 0.95,
      icon: "w-5 h-5 mr-3",
      iconMaterial: "mr-3"
    },
    group6: {
      termsContainer: "flex-row flex-wrap justify-center items-center mt-2 px-4",
      termsText: "text-base text-gray-600 text-center",
      termsLink: "text-base text-[#4051FF] text-center",
      screen: "flex-1 bg-white",
      subscribeBanner: "absolute w-full bg-black pt-14 sm:pt-16 pb-3 items-center justify-center active:bg-neutral-800 active:scale-[0.98]",
      subscribeBannerText: "text-white text-sm sm:text-base",
      mainWrapper: "flex-[2] px-12 pt-40 items-center justify-center",
      contentWrapper: "w-full",
      bottomWrapper: "flex-1 px-16 justify-start pt-5 mb-7",
      headerText: "text-4xl text-center px-6 mb-6 font-bold text-black",
      subHeader: "px-6 text-lg mb-6",
      subHeaderText: "text-gray-800 text-center",
      authButton: "py-4 px-4 flex-row items-center justify-center rounded-[10px] mb-6",
      authButtonText: "text-lg font-medium",
      authButtonActive: "bg-black active:bg-neutral-800 active:scale-[0.98]",
      authButtonTextColor: "text-white",
      videoView: "mt-4",
      videoViewContainer: "items-center justify-center",
      videoHeight: 260,
      videoWidth: width * 0.95,
      icon: "w-5 h-5 mr-3",
      iconMaterial: "mr-3"
    },
    group7: {
      termsContainer: "flex-row flex-wrap justify-center items-center mt-3 px-4",
      termsText: "text-base text-gray-600 text-center",
      termsLink: "text-base text-[#4051FF] text-center",
      screen: "flex-1 bg-white",
      subscribeBanner: "absolute w-full bg-black pt-14 sm:pt-16 pb-3 items-center justify-center active:bg-neutral-800 active:scale-[0.98]",
      subscribeBannerText: "text-white text-sm sm:text-base",
      mainWrapper: "flex-[2] px-12 pt-40 items-center justify-center",
      contentWrapper: "w-full",
      bottomWrapper: "flex-1 px-16 justify-start pt-7 mb-7",
      headerText: "text-4xl text-center px-6 mb-6 font-bold text-black",
      subHeader: "px-2 text-lg mb-6",
      subHeaderText: "text-gray-800 text-center",
      authButton: "py-4 px-4 flex-row items-center justify-center rounded-[10px] mb-6",
      authButtonText: "text-lg font-medium",
      authButtonActive: "bg-black active:bg-neutral-800 active:scale-[0.98]",
      authButtonTextColor: "text-white",
      videoView: "mt-4",
      videoViewContainer: "items-center justify-center",
      videoHeight: 260,
      videoWidth: width * 0.95,
      icon: "w-5 h-5 mr-3",
      iconMaterial: "mr-3"
    },
    group8: {
      termsContainer: "flex-row flex-wrap justify-center items-center mt-2 px-4",
      termsText: "text-base text-gray-600 text-center",
      termsLink: "text-base text-[#4051FF] text-center",
      screen: "flex-1 bg-white",
      subscribeBanner: "absolute w-full bg-black pt-14 sm:pt-16 pb-3 items-center justify-center active:bg-neutral-800 active:scale-[0.98]",
      subscribeBannerText: "text-white text-sm sm:text-base",
      mainWrapper: "flex-[2] px-12 pt-36 items-center justify-center",
      contentWrapper: "w-full",
      bottomWrapper: "flex-1 px-16 justify-start pt-4 mb-7",
      headerText: "text-4xl text-center mb-6 px-10 font-bold text-black",
      subHeader: "px-6 text-lg mb-6",
      subHeaderText: "text-gray-800 text-center",
      authButton: "py-4 px-4 flex-row items-center justify-center rounded-[10px] mb-6",
      authButtonText: "text-lg font-medium",
      authButtonActive: "bg-black active:bg-neutral-800 active:scale-[0.98]",
      authButtonTextColor: "text-white",
      videoView: "mt-4",
      videoViewContainer: "items-center justify-center",
      videoHeight: 260,
      videoWidth: width * 0.95,
      icon: "w-5 h-5 mr-3",
      iconMaterial: "mr-3"
    },
    group9: {
      termsContainer: "flex-row flex-wrap justify-center items-center mt-4 px-4",
      termsText: "text-base text-gray-600 text-center",
      termsLink: "text-base text-[#4051FF] text-center",
      screen: "flex-1 bg-white",
      subscribeBanner: "absolute w-full bg-black pt-14 sm:pt-16 pb-3 items-center justify-center active:bg-neutral-800 active:scale-[0.98]",
      subscribeBannerText: "text-white text-sm sm:text-base",
      mainWrapper: "flex-[2] px-12 pt-36 items-center justify-center",
      contentWrapper: "w-full",
      bottomWrapper: "flex-1 px-16 justify-start pt-3 mb-7",
      headerText: "text-4xl text-center px-10 mb-6 font-bold text-black",
      subHeader: "px-6 text-lg mb-6",
      subHeaderText: "text-gray-800 text-center",
      authButton: "py-4 px-4 flex-row items-center justify-center rounded-[10px] mb-6",
      authButtonText: "text-lg font-medium",
      authButtonActive: "bg-black active:bg-neutral-800 active:scale-[0.98]",
      authButtonTextColor: "text-white",
      videoView: "mt-4",
      videoViewContainer: "items-center justify-center",
      videoHeight: 260,
      videoWidth: width * 0.95,
      icon: "w-5 h-5 mr-3",
      iconMaterial: "mr-3"
    },
    group10: {
      termsContainer: "flex-row flex-wrap justify-center items-center mt-4 px-4",
      termsText: "text-base text-gray-600 text-center",
      termsLink: "text-base text-[#4051FF] text-center",
      screen: "flex-1 bg-white",
      subscribeBanner: "absolute w-full bg-black pt-14 sm:pt-16 pb-3 items-center justify-center active:bg-neutral-800 active:scale-[0.98]",
      subscribeBannerText: "text-white text-sm sm:text-base",
      mainWrapper: "flex-[2] px-12 pt-32 items-center justify-center",
      contentWrapper: "w-full",
      bottomWrapper: "flex-1 px-16 justify-start pt-2 mb-7",
      headerText: "text-4xl text-center mb-6 px-12 font-bold text-black",
      subHeader: "px-6 text-lg mb-6",
      subHeaderText: "text-gray-800 text-center",
      authButton: "py-4 px-4 flex-row items-center justify-center rounded-[10px] mb-6",
      authButtonText: "text-lg font-medium",
      authButtonActive: "bg-black active:bg-neutral-800 active:scale-[0.98]",
      authButtonTextColor: "text-white",
      videoView: "mt-4",
      videoViewContainer: "items-center justify-center",
      videoHeight: 260,
      videoWidth: width * 0.95,
      icon: "w-5 h-5 mr-3",
      iconMaterial: "mr-3"
    },
    unknown: {
      termsContainer: "flex-row flex-wrap justify-center items-center mt-4 px-4",
      termsText: "text-xs text-gray-600 text-center",
      termsLink: "text-xs text-[#4051FF] text-center",
      screen: "flex-1 bg-white",
      subscribeBanner: "absolute w-full bg-black pt-14 sm:pt-16 pb-3 items-center justify-center active:bg-neutral-800 active:scale-[0.98]",
      subscribeBannerText: "text-white text-sm sm:text-base",
      mainWrapper: "flex-[2] px-12 pt-44 items-center justify-center",
      contentWrapper: "w-full",
      bottomWrapper: "flex-1 px-16 justify-start pt-5 mb-7",
      headerText: "text-4xl text-center mb-6 font-bold text-black",
      subHeader: "px-6 text-lg mb-6",
      subHeaderText: "text-gray-800 text-center",
      authButton: "py-4 px-4 flex-row items-center justify-center rounded-[10px] mb-6",
      authButtonText: "text-lg font-medium",
      authButtonActive: "bg-black active:bg-neutral-800 active:scale-[0.98]",
      authButtonTextColor: "text-white",
      videoView: "mt-4",
      videoViewContainer: "items-center justify-center",
      videoHeight: 260,
      videoWidth: width * 0.95,
      icon: "w-5 h-5 mr-3",
      iconMaterial: "mr-3"
    }
  };

  return deviceGroupStyles[deviceGroup];
};