import { getDeviceGroup } from "../utils/device";

export const getStyles = (width, height) => {
  const deviceGroup = getDeviceGroup(width, height);

  console.log(deviceGroup);
  
  const deviceGroupStyles = {
    group1: {
        container: "flex-1 bg-gray-100 ",
      loadingContainer: "flex-1 justify-center items-center bg-white",
      loadingText: "mt-2.5 text-sm text-black",
      content: "flex-1 pt-20",
      contentContainer: "px-3",
      card: "bg-white rounded-xl p-4 my-2 shadow",
      formContainer: "w-full ",
      heading: "text-[20px] font-medium mb-6",
      inputGroup: "mb-5",
      label: " mb-1.5 text-gray-800",
      unitText: "text-xs text-gray-500",
      input: "border border-gray-300 rounded-lg p-3  bg-white text-gray-800",
      measurementsSection: "mt-2 mb-2",
      sectionTitle: "text-base font-normal mb-3 text-gray-800",
      button: "bg-[#6666FF] rounded-[10px] px-3 py-4 items-center mt-4",
      buttonText: "text-white  font-normal",
      resultContainer: "p-4",
      resultHeader: "flex-row justify-between items-center mb-5",
      resultTitle: "text-xl font-normal text-gray-800",
      resultContent: "items-center",
      sizeText: "text-lg font-normal text-gray-800",
      bottomPadding: "h-28"
    },
    group2: {
        container: "flex-1 bg-gray-100 ",
        loadingContainer: "flex-1 justify-center items-center bg-white",
        loadingText: "mt-2.5 text-sm text-black",
        content: "flex-1 pt-20",
        contentContainer: "px-3",
        card: "bg-white rounded-xl p-4 my-2 shadow",
        formContainer: "w-full ",
        heading: "text-[20px] font-medium mb-6",
        inputGroup: "mb-5",
        label: " mb-1.5 text-gray-800",
        unitText: "text-xs text-gray-500",
        input: "border border-gray-300 rounded-lg p-3  bg-white text-gray-800",
        measurementsSection: "mt-2 mb-2",
        sectionTitle: "text-base font-normal mb-3 text-gray-800",
        button: "bg-[#6666FF] rounded-[10px] px-3 py-4 items-center mt-4",
        buttonText: "text-white  font-normal",
        resultContainer: "p-4",
        resultHeader: "flex-row justify-between items-center mb-5",
        resultTitle: "text-xl font-normal text-gray-800",
        resultContent: "items-center",
        sizeText: "text-lg font-normal text-gray-800",
        bottomPadding: "h-28"
    },
    group3: {
        container: "flex-1 bg-gray-100 ",
      loadingContainer: "flex-1 justify-center items-center bg-white",
      loadingText: "mt-2.5 text-sm text-black",
      content: "flex-1 pt-20",
      contentContainer: "px-3",
      card: "bg-white rounded-xl p-4 my-2 shadow",
      formContainer: "w-full ",
      heading: "text-[20px] font-medium mb-6",
      inputGroup: "mb-5",
      label: " mb-1.5 text-gray-800",
      unitText: "text-xs text-gray-500",
      input: "border border-gray-300 rounded-lg p-3  bg-white text-gray-800",
      measurementsSection: "mt-2 mb-2",
      sectionTitle: "text-base font-normal mb-3 text-gray-800",
      button: "bg-[#6666FF] rounded-[10px] px-3 py-4 items-center mt-4",
      buttonText: "text-white  font-normal",
      resultContainer: "p-4",
      resultHeader: "flex-row justify-between items-center mb-5",
      resultTitle: "text-xl font-normal text-gray-800",
      resultContent: "items-center",
      sizeText: "text-lg font-normal text-gray-800",
      bottomPadding: "h-28"
    },
    group4: {
        container: "flex-1 bg-gray-100",
        loadingContainer: "flex-1 justify-center items-center bg-white",
        loadingText: "mt-2.5 text-2xl text-black",
        content: "flex-1 pt-20",
        contentContainer: "px-4",
        card: "bg-white rounded-xl p-4 my-2.5 shadow",
        formContainer: "w-full mt-3 ",
        heading: "text-[20px] font-medium mb-4",
        inputGroup: "mb-5",
        label: "text-base mb-2 text-gray-800",
        unitText: "text-sm text-gray-500",
        input: "border border-gray-300 rounded-lg p-4  bg-white text-gray-800",
        measurementsSection: "mt-2 mb-2",
        sectionTitle: "text-lg font-normal mb-3 text-gray-800",
        button: "bg-[#6666FF] rounded-[10px] p-4 items-center mt-5",
        buttonText: "text-white  font-normal",
        resultContainer: "p-4",
        resultHeader: "flex-row justify-between items-center mb-6",
        resultTitle: "text-2xl font-normal text-gray-800",
        resultContent: "items-center",
        sizeText: "text-xl font-normal text-gray-800",
        bottomPadding: "h-28"
    },
    group5: {
        container: "flex-1 bg-gray-100",
      loadingContainer: "flex-1 justify-center items-center bg-white",
      loadingText: "mt-2.5 text-2xl text-black",
      content: "flex-1 pt-20",
      contentContainer: "px-4",
      card: "bg-white rounded-xl p-4 my-2.5 shadow",
      formContainer: "w-full",
      heading: "text-[20px] font-medium mb-4",
      inputGroup: "mb-5",
      label: "text-base mb-2 text-gray-800",
      unitText: "text-sm text-gray-500",
      input: "border border-gray-300 rounded-lg p-4  bg-white text-gray-800",
      measurementsSection: "mt-2 mb-2",
      sectionTitle: "text-lg font-normal mb-3 text-gray-800",
      button: "bg-[#6666FF] rounded-[10px] p-4 items-center mt-5",
      buttonText: "text-white  font-normal",
      resultContainer: "p-4",
      resultHeader: "flex-row justify-between items-center mb-6",
      resultTitle: "text-2xl font-normal text-gray-800",
      resultContent: "items-center",
      sizeText: "text-xl font-normal text-gray-800",
      bottomPadding: "h-28"
    },
    group6: {
        container: "flex-1 bg-gray-100",
      loadingContainer: "flex-1 justify-center items-center bg-white",
      loadingText: "mt-2.5 text-2xl text-black",
      content: "flex-1 pt-20",
      contentContainer: "px-4",
      card: "bg-white rounded-xl p-4 my-2.5 shadow",
      formContainer: "w-full",
      heading: "text-[20px] font-medium mb-4",
      inputGroup: "mb-5",
      label: "text-base mb-2 text-gray-800",
      unitText: "text-sm text-gray-500",
      input: "border border-gray-300 rounded-lg p-4  bg-white text-gray-800",
      measurementsSection: "mt-2 mb-2",
      sectionTitle: "text-lg font-normal mb-3 text-gray-800",
      button: "bg-[#6666FF] rounded-[10px] p-4 items-center mt-5",
      buttonText: "text-white  font-normal",
      resultContainer: "p-4",
      resultHeader: "flex-row justify-between items-center mb-6",
      resultTitle: "text-2xl font-normal text-gray-800",
      resultContent: "items-center",
      sizeText: "text-xl font-normal text-gray-800",
      bottomPadding: "h-28"
    },
    group7: {
        container: "flex-1 bg-gray-100",
      loadingContainer: "flex-1 justify-center items-center bg-white",
      loadingText: "mt-2.5 text-2xl text-black",
      content: "flex-1 pt-20",
      contentContainer: "px-4",
      card: "bg-white rounded-xl p-4 my-2.5 shadow",
      formContainer: "w-full",
      heading: "text-[20px] font-medium mb-4",
      inputGroup: "mb-5",
      label: "text-base mb-2 text-gray-800",
      unitText: "text-sm text-gray-500",
      input: "border border-gray-300 rounded-lg p-4  bg-white text-gray-800",
      measurementsSection: "mt-2 mb-2",
      sectionTitle: "text-lg font-normal mb-3 text-gray-800",
      button: "bg-[#6666FF] rounded-[10px] p-4 items-center mt-5",
      buttonText: "text-white  font-normal",
      resultContainer: "p-4",
      resultHeader: "flex-row justify-between items-center mb-6",
      resultTitle: "text-2xl font-normal text-gray-800",
      resultContent: "items-center",
      sizeText: "text-xl font-normal text-gray-800",
      bottomPadding: "h-28"
    },
    group8: {
        container: "flex-1 bg-gray-100",
      loadingContainer: "flex-1 justify-center items-center bg-white",
      loadingText: "mt-2.5 text-2xl text-black",
      content: "flex-1 pt-20",
      contentContainer: "px-4",
      card: "bg-white rounded-xl p-4 my-2.5 shadow",
      formContainer: "w-full",
      heading: "text-[20px] font-medium mb-4",
      inputGroup: "mb-5",
      label: "text-base mb-2 text-gray-800",
      unitText: "text-sm text-gray-500",
      input: "border border-gray-300 rounded-lg p-4  bg-white text-gray-800",
      measurementsSection: "mt-2 mb-2",
      sectionTitle: "text-lg font-normal mb-3 text-gray-800",
      button: "bg-[#6666FF] rounded-[10px] p-4 items-center mt-5",
      buttonText: "text-white  font-normal",
      resultContainer: "p-4",
      resultHeader: "flex-row justify-between items-center mb-6",
      resultTitle: "text-2xl font-normal text-gray-800",
      resultContent: "items-center",
      sizeText: "text-xl font-normal text-gray-800",
      bottomPadding: "h-28"
    },
    group9: {
        container: "flex-1 bg-gray-100",
      loadingContainer: "flex-1 justify-center items-center bg-white",
      loadingText: "mt-2.5 text-2xl text-black",
      content: "flex-1 pt-20",
      contentContainer: "px-4",
      card: "bg-white rounded-xl p-4 my-2.5 shadow",
      formContainer: "w-full",
      heading: "text-[20px] font-medium mb-4",
      inputGroup: "mb-5",
      label: "text-base mb-2 text-gray-800",
      unitText: "text-sm text-gray-500",
      input: "border border-gray-300 rounded-lg p-4  bg-white text-gray-800",
      measurementsSection: "mt-2 mb-2",
      sectionTitle: "text-lg font-normal mb-3 text-gray-800",
      button: "bg-[#6666FF] rounded-[10px] p-4 items-center mt-5",
      buttonText: "text-white  font-normal",
      resultContainer: "p-4",
      resultHeader: "flex-row justify-between items-center mb-6",
      resultTitle: "text-2xl font-normal text-gray-800",
      resultContent: "items-center",
      sizeText: "text-xl font-normal text-gray-800",
      bottomPadding: "h-28"
    },
    group10: {
        container: "flex-1 bg-gray-100",
        loadingContainer: "flex-1 justify-center items-center bg-white",
        loadingText: "mt-2.5 text-2xl text-black",
        content: "flex-1 pt-20",
        contentContainer: "px-4",
        card: "bg-white rounded-xl p-4 my-2.5 shadow",
        formContainer: "w-full",
        heading: "text-[20px] font-medium mb-4",
        inputGroup: "mb-5",
        label: "text-base mb-2 text-gray-800",
        unitText: "text-sm text-gray-500",
        input: "border border-gray-300 rounded-lg p-4  bg-white text-gray-800",
        measurementsSection: "mt-2 mb-2",
        sectionTitle: "text-lg font-normal mb-3 text-gray-800",
        button: "bg-[#6666FF] rounded-[10px] p-4 items-center mt-5",
        buttonText: "text-white  font-normal",
        resultContainer: "p-4",
        resultHeader: "flex-row justify-between items-center mb-6",
        resultTitle: "text-2xl font-normal text-gray-800",
        resultContent: "items-center",
        sizeText: "text-xl font-normal text-gray-800",
        bottomPadding: "h-28"
    },
    unknown: {
        container: "flex-1 bg-white",
        loadingContainer: "flex-1 justify-center items-center bg-white",
        loadingText: "mt-2.5 text-2xl text-black",
        content: "flex-1 pt-14 ",
        contentContainer: "px-1.5",
        bottomPadding: "h-20"
    }
  };

  return deviceGroupStyles[deviceGroup];
};