default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    increment_build_number(
      xcodeproj: "ios/MyFittingRoomAI.xcodeproj"
    )

    build_app(
      workspace: "ios/MyFittingRoomAI.xcworkspace",
      scheme: "MyFittingRoomAI",
      configuration: "Release",
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
