export const Fonts = {
    Black: 'Switzer-Black',
    BlackItalic: 'Switzer-BlackItalic',
    Bold: 'Switzer-Bold',
    BoldItalic: 'Switzer-BoldItalic',
    ExtraBold: 'Switzer-Extrabold',
    ExtraBoldItalic: 'Switzer-ExtraboldItalic',
    ExtraLight: 'Switzer-Extralight',
    ExtraLightItalic: 'Switzer-ExtralightItalic',
    Italic: 'Switzer-Italic',
    Light: 'Switzer-Light',
    LightItalic: 'Switzer-LightItalic',
    Medium: 'Switzer-Medium',
    MediumItalic: 'Switzer-MediumItalic',
    Regular: 'Switzer-Regular',
    SemiBold: 'Switzer-Semibold',
    SemiBoldItalic: 'Switzer-SemiboldItalic',
    Thin: 'Switzer-Thin',
    ThinItalic: 'Switzer-ThinItalic',
};
